[package]
version = "0.0.14"

name = "libharu_ng"
description = "Generate PDFs with Rust using libharu"
authors = ["Bastian Bense <bb@neosw.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bastibense/libharu_ng"
homepage = "https://github.com/bastibense/libharu_ng"
categories = ["external-ffi-bindings", "api-bindings"]

edition = "2021"
build = "build.rs"

exclude = [
  ".github",
  ".gitignore",
  ".dockerignore",
  "Dockerfile",
  "*.code-workspace",
]

[dependencies]
