name: Build, test and publish

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -f Dockerfile.cratesio -t libharu_ng . --build-arg="CRATESIO_TOKEN=${{ secrets.CRATESIO_TOKEN }}"
